### ISSUE TITLE
Add support for code completion inside text block templates

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.ui#1038]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1711 adds support inside String templates. The present ticket is for text block templates.

I think there are some differences between text block handling between Scanner and CompletionScanner that needs reconciling. It is best to simply use the scanner implementation via a super call and cover for any additional behaviors needed rather than duplicate the body. In comparing the scanForTextBlock between Scanner and CompletionScanner I already see 4-5 bug fixes that happened only in one place!

**Comment by jarthana** [comment]
OK, it appears that there's this notion called partitions inside jdt.ui that needs to be updated in order to even invoke the CU.complete() in jdt.core. I found CompletionProposalComputerDescriptor to be one such place to add new partition for IJavaPartitions.JAVA_MULTI_LINE_STRING, but that's not all. Looks like this is more involved and only for a jdt.ui expert.

Once this is taken care of, all we will have to do in jdt.core is to get rid of the CompletionScanner#scanForTextBlock().

**Comment by srikanth-sankaran** [comment]
@noopur2507 @jjohnstn - FYI, this needs fixing before _any_ code completion will work for text block templates.

**Comment by jarthana** [comment]
> Once this is taken care of, all we will have to do in jdt.core is to get rid of the CompletionScanner#scanForTextBlock().

JDT Core changes are here - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1803
The tests test the jdt.core part alone. The completion won't work inside editor until this issue is resolved.

**Comment by noopur2507** [comment]
Copying @ktatavarthi also who had worked on a similar feature earlier, to provide any hints for this one.
