### ISSUE TITLE
How to set 'enable preview' for Java 22

### ISSUE THREAD

**Issue by MyhreAndersen** [eclipse-jdt/eclipse.jdt.ui#1174]
Goto: Properties -> Java Compiler -> JDK Compliance
It is impossible to set level 22

I am using Eclipse 2024-3 ( Version: 2024-03 M2 (4.31.0 M2) ).

**Comment by robstryker** [comment]
Work on java-22 has not yet been merged into any milestone or nightly build at this time.

**Comment by MyhreAndersen** [comment]
Do you have an idea when java 22 will be in eclipse ?

**Comment by noopur2507** [comment]
> Do you have an idea when java 22 will be in eclipse ?

Support for Java 22 will be available as a Marketplace entry and will be merged into nightly builds after Java 22 GA on 19th March. Currently, the work is in progress under BETA_JAVA22 branches. You can use the update site https://download.eclipse.org/eclipse/updates/4.31-Y-builds/ to try it out. Please check existing issues for the Java 22 items that are still under development before raising new ones for the same.

**Comment by mpalat** [comment]
At this point there are no Java 22 features that are available in the branch and is still under development - only some infrastructure changes are available in that branch - you can track the progress of compiler part of the work here - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1397. I would strongly recommend to wait for the Marketplace entry rather than trying out the Y builds unless you want to experiment with a dev branch.
