### ISSUE TITLE
Implement methods quickfix on records should not create stubs for equals, hashCode and toString

### ISSUE THREAD

**Issue by szarnekow** [eclipse-jdt/eclipse.jdt.ui#161]
```java
record MyRecord(Object o) implements Comparable<MyRecord> {
}
```

Invoking the quickfix to add the missing members unexpectedly yields
```java
record MyRecord(Object o) implements Comparable<MyRecord> {

	@Override
	public int compareTo(MyRecord o) {
		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		return false;
	}

	@Override
	public int hashCode() {
		return 0;
	}

	@Override
	public String toString() {
		return null;
	}
	
}
```

**Comment by tsmaeder** [comment]
`StubUtility2Core#getUnimplementedMethods(...)` incorrectly adds the synthetic record methods to the set of methods to implement: the super class of all records is `java.lang.Record`, which contains abstract methods for `equals`, `hashCode` and `toString()`. It seems to me that something being implemented with a synthetic method should remove the need for it to be implemented. The alternative fix would be to special-case `java.lang.Record` in order to ignore all methods declared there.

**Comment by tsmaeder** [comment]
Further error case: when we implement an interface that has the same name as a property, implementing methods also adds those methods, even if the compiler generates them: example:
```
record foo(void run) implement Runnable {
}
```

will add a `void run()` method.

**Comment by jjohnstn** [comment]
I agree that getUnimplementedMethods() is not correct for the record.  Those methods are implemented.  I also think that the bug referenced is not unreasonable in creating the stubs as asked since the vast majority of users won't ever select that when creating a record.  That said, I think that a new method should be added to StubUtility to support the creationg dialog so both situations work as expected.

**Comment by jjohnstn** [comment]
Verified for 4.25 M3 using I20220817-0600 build
