### ISSUE TITLE
[Enhancement] Add quickfix option to rename unused patterns to _

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.ui#1701]
From: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3051

JDT core added a warning for unused patterns. It would be helpful to add a "rename unused variable to _" option on hover or on ctrl+1. This will help with batch renaming to transition old code to new code.

**Comment by srikanth-sankaran** [comment]
Please note: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3055 also introduces an API option to control whether unused lambda parameters should be complained against. 

The option string is declared as:

public static final String OPTION_ReportUnusedLambdaParameter = "org.eclipse.jdt.core.compiler.problem.unusedLambdaParameter";

Please include UI support for configuring this option too as a part of this ticket.

Note: This option has an effect only on JDK22 and upwards. For 21 and below, the compiler does not emit the unused lambda parameter warning - since these are not actionable.

**Comment by noopur2507** [comment]
> Please note: [eclipse-jdt/eclipse.jdt.core#3055](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3055) also introduces an API option to control whether unused lambda parameters should be complained against.
> 
> The option string is declared as:
> 
> public static final String OPTION_ReportUnusedLambdaParameter = "org.eclipse.jdt.core.compiler.problem.unusedLambdaParameter";
> 
> Please include UI support for configuring this option too as a part of this ticket.
> 
> Note: This option has an effect only on JDK22 and upwards. For 21 and below, the compiler does not emit the unused lambda parameter warning - since these are not actionable.

Moved to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1721.

**Comment by jjohnstn** [comment]
Hi @noopur2507 I have a patch for this that should be ready tomorrow (just need to add some tests).  Hopefully, you aren't working on a fix at the same time.

**Comment by noopur2507** [comment]
> Hi @noopur2507 I have a patch for this that should be ready tomorrow (just need to add some tests). Hopefully, you aren't working on a fix at the same time.

Thanks, Jeff. I have not started working on the quick fix.
