### ISSUE TITLE
Add generators to the quick fix / assists for the class 

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#281]
The assists pop-up on a Java class still contains only a few entries. What not adding the generate entries also the quick fixes?

![image](https://user-images.githubusercontent.com/139910/192472445-c9b59e55-5fe8-488b-9068-749b4be492ac.png)

![image](https://user-images.githubusercontent.com/139910/192472597-a7c1ce9e-018c-40c1-bf40-2237bdad7f8c.png)

**Comment by vogella** [comment]
cc @jjohnstn

**Comment by jjohnstn** [comment]
Not sure about all of them.  I think there's a precedent for Generate Getters and Setters because the Quick Fix for a field that doesn't already have a getter/setter offers to create one so it makes sense to offer this for the class.  Of the remaining ones in your list, I could see Override/Implement Methods and possibly hashCode() and equals(), but I don't think the others are important enough and we don't want a cluttered list.

@noopur2507 What do you think?

**Comment by vogella** [comment]
I think the most important (for me) would be:

Getter / Setter (per field is not super easy to use)
hashCode()
Equals()
toString()

The Override / implement Method wizard is rarely used by me, but adding it would most likely also helpful to others.

Thanks @jjohnstn for considering this. IntelliJ has a popup and shortcut for these generations, would be nice to have this as quick fix in Eclipse.

**Comment by vogella** [comment]
Thanks @jjohnstn what about the hashCode/ equals and toString generators?

**Comment by jjohnstn** [comment]
Still to come.  Otherwise, I would have closed the issue.

**Comment by jjohnstn** [comment]
@vogella I think this can be closed now unless you have any issues.  I will leave the implement/override methods to be accessible via the Source menu.

**Comment by vogella** [comment]
Thanks Jeff, looks great

**Comment by jjohnstn** [comment]
Verified for 4.26 M3 using I20221108 build.

**Comment by ktatavarthi** [comment]
@jjohnstn Can you please add N&N entries for these new Quick assists.
