### ISSUE TITLE
Improve the Safety of "Extract Local Variable" Refactorings by Identifying the Side Effect of Selected Expression

### ISSUE THREAD

**Issue by chixiaye** [eclipse-jdt/eclipse.jdt.ui#348]
# Improve the Safety of "Extract Local Variable" Refactorings by Identifying the Side Effect of Selected Expression

# Description
"Extract Variable" refactoring in Eclipse provides an option to replace all occurrences of the selected expression with references to the newly extracted local variable. However, it may result in semantic errors when the selected expression (to be extracted as a variable) has side effect, i.e., it may change the states of the system. 

 A simple and straightforward example is `Lines[i++]`: 

```java
1   /* CS1: Original Code Snippet */
2   String[] Lines;
3   int i;
4   private String foo(String msg) {
5   	return msg+": "+ Lines[i++];
6   }
7   ...
8   log.warn(foo("Format warning"));
9   ...
10  log.warn(foo("Format warning"));
```
Extracting `foo("Format warning")` as local variable (enabling "replace all occurrences") would result in the following code:

```java
1   /* CS2: Code Snippet After Refactoring */
2   String[] Lines;
3   int i;
4   private String foo(String msg) {
5   	return msg+": "+ Lines[i++];
6   }
7   ...
8   String foo= foo("Format warning");
9   log.warn(foo);
10  ...
11  log.warn(foo);
```
The resulting code is semantically different from the original code, which results in semantic errors. 

# Solution
We should check the potential side effect of the selected expression before the actual conduction of the Extract Local Variable refactoring. 

The key of the checking is composed of two parts. The first is to identify all statements that may be executed by the selected expression, which may include the expression itself and all statements directly or indirectly invoked by the expression. To guarantee the performance of the IDE, we would confine the method call stack to the first four levels (if there are any).  

The second part is to validate whether the collected statements would change any status of the systems, i.e., updating variables/parameters/fields or generating outputs.   Notably, if we cannot access the body of the method invoked by the retrieved statements, we simply assume the method is safe (having no side effect) to minimize the chance of false alarms. 

To guarantee the performance (response time) of the refactoring engine, we can set a maximum analyzing time (e.g., 3 or 5 seconds). If the analysis terminates within the given time slot, that is fine. If fail, it would return what the current version of Eclipse returns (i.e., allowing the extracting of the selected expression).

**The above is our proposed solution, if you have any comments or suggestions, please let us know.**

**Comment by chixiaye** [comment]
@jjohnstn We have added a new issue, could you please check if our solution meets your expectations and requirements? Thank you so much.

**Comment by jjohnstn** [comment]
I think that protecting all method call scenarios would be too significant a cost to do each time and in the end, it still is "user beware" as you might still run out of time.  Any method call that has side-effects should probably document them in its Javadoc and the user can discover this by hovering over the method name.  That said, you could scan just the single method itself (no following method calls) and look for field, input variable, and static variable changes.  Not sure about looking for outputs as these might be false positives in that they are error messages not meant to occur or output gets overwritten with the same data over and over again.  Even obvious side-effects may not occur (e.g. an error counter protected by an if statement).  To that end, you could issue a warning dialog that "possible side-effects are detected, do you wish to continue?"  Beyond direct changes in the method and call itself, I think it is fair to treat other scenarios as "user beware" (remember the user is manually choosing to extract the call into a local variable).  You could also add additional support to check expressions using the ASTNodes.isPassive() method.  This would screen out such obvious cases like extracting a[x++].

**Comment by liuhuigmail** [comment]
@jjohnstn  Thank you for quick response. So, we should 
1. Validate the selected expression with ASTNodes.isPassive() first
2. If the selected expression contains any method invocation, we scan just the invoked methods themselves (no following method calls) and look for field, input variable, and static variable changes. 

@chixiaye  Would you please kindly prepare a pull request according to the preceding description? Thank you.

**Comment by jjohnstn** [comment]
Just to clarify point 1: you need to check any expression that is part of the selection (the selection might not be an expression itself but may have expressions in it  e.g. a[i++].getInteger()).

**Comment by chixiaye** [comment]
Got it. I will prepare PR based on your suggestions. THX a lot.

**Comment by jjohnstn** [comment]
Hi, I was off for the holidays.  Regarding the latest patch, sorry I wasn't clear above.  If you know there are side-effects that will change the logic, you should not make the change (e.g. if you have code with a[i++] + a[i++] then you should not extract the a[i++] in this case as it is a logic change to replace both references with one local variable).  In this case, you shouldn't ask the end-user.  You could, if you want, do the extraction if there was only one instance replaced as you know that the logic hasn't changed unless you move it before a reference to i.  Only in the case where you don't know if you have side-effects should you ask the user.  So, if you have a method call to extract and you scan the method but find nothing then you can go ahead but if that method has other method calls that you don't follow and scan as mentioned earlier, then you can qualify this as "potential side-effects" and ask if the user wants to continue.   I think for your method scanning you could add some common Java library methods as clean to reduce the odds of asking the end-user (e.g. consider java.lang.String methods as clean) so if a method just called String methods and didn't assign the output of such calls to cause side-effects, then it would be considered clean.  I would suggest you make the user message more specific since it will only involve method calls.  For example, "The extraction will contain a method call that may cause side-effects, do you wish to continue?")

**Comment by chixiaye** [comment]
Thank you very much for your comments. I'm sorry for not clarifying the patch. Your suggestions will guarantee the accuracy of refactoring, but I have the following two concerns. 

First, in my opinion, when we think that an extracted expression has side effects, it may not happen all the time. So extracting multiple expressions does not necessarily lead to a change in semantics. For example,
```java  
int i= getAndAdd(0);
int j= getAndAdd(0);
...
getAndAdd(int cnt){
    int res= this.value;
    this.value+= cnt;
    return res;
}
```  
In our algorithm, the method `getAndAdd` is considered to have side effects. Extracting `getAndAdd(0)` would not lead to a change in semantics obviously. But in another case, if the expression `getAndAdd(1)` was selected, the semantics of the code would be changed. Although data flow and control flow analysis can solve this problem, the computational cost is huge. For this kind of side effect expression, we are certain to some extent, I think it would be more appropriate to warn the user. Of course, for expressions that do not involve function calls that have potential side effects, like `a[i++]`, we can directly extract only a single expression. For example,
```java  
return a[++i] + a[++i] + a[++i];
```  
Select the first `a[++i]` expression and open replace all option to do refactoring, the right result would be:
```java
int v= a[++i]; 
return v + a[++i] + a[++i];
```

Second, regarding function calls whose side effects cannot be judged, my concern is that introducing too often warning messages will make the user experience bad. Because just marking some common methods may not be enough. In a real Java development project, it is inevitable to use external APIs and utilize Java polymorphism. I think that the ambiguous functions can be seen as having no side effects (most of them truly do not). And for the methods like `print`,`log`,`currentTimeMillis` ... we can send a warning message to the user.

The above are some of my personal opinions. I sincerely look forward to reaching an aggrement.

**Comment by jjohnstn** [comment]
Hi @chixiaye.  Thanks for the update.  I like your idea to only make one change for an expression with known side-effects.  That way a user will see a change but it won't change the logic.  I think you should take the same approach with a method that has direct side-effects as well (rather than a warning).  Otherwise, the user is forced to know the logic of the method that is being called or look up its source in the middle of the change which isn't feasible.  I think in both cases, you should check for the "change all occurrences" preference and if it is enabled and there is more than one usage in the file to change, issue a log message or a dialog that tells the user only one instance can be extracted due to side-effects.  Now, the user has all the info needed and no difficult decision to make.  Regarding methods with no direct side-effects, I am fine with your idea of making the change without a warning, but if you find calls to print, etc.. that you know cause side-effects, then the rules above apply.  What do you think?

**Comment by chixiaye** [comment]
Glad to receive your response and thank you so much for your suggestions. Warnings make users recheck the code, which really increases the user's cost.

In the following, based on your suggestions, I would illustrate the refactoring with some specific examples. If any ideas differ from yours or misunderstand what you meant, please let me know. In these examples, `replace all occurrences` option is opened. 

#### Example-1: Expression does have side effects
```java  
return arr[i++] + arr[i++];
```
Select the first expression `arr[i++]` and do refactoring. Only one expression was extracted as follows, and a dialog(information dialog rather than warning dialog) would pop up to remind the user like `Only one expression can be extracted due to side-effects`.
```java  
int v= arr[i++];
return v + arr[i++];
```

#### Example-2: Expression that contains side-effects method invocation
```java  
return inc() + inc();
int inc(){
    return ++this.value;
}
```
Select the first expression `inc()` and do refactoring. Only one expression was extracted, and a dialog would pop up as well.
```java  
int v= inc();
return v + inc();
int inc(){
    return ++this.value;
}
```

#### Example-3: Expression that's not sure about side effects
```java  
System.out.println(list.size()+","+list.size());
```
Select the first expression `list.size()` and do refactoring. All two expressions were extracted.
```java  
int v= list.size();
System.out.println(v+","+v);
```

#### Example-4: Expression that contains marked methods 
```java  
long start= System.currentTimeMillis();
...
if(System.currentTimeMillis() - start < slot){
    ...
}
```
Select the second expression `System.currentTimeMillis()` and do refactoring. Only the selected expression was extracted, and a dialog would pop up.
```java  
long start= System.currentTimeMillis();
...
long v= System.currentTimeMillis();
if(v - start < slot){
    ...
}
```

BTW, a patch was resubmitted in [ClassCast PR](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/333). Could you kindly check the patch? Thanks a lot.

**Comment by jjohnstn** [comment]
Hi @chixiaye.  That looks good.  Will look at the patch.

**Comment by liuhuigmail** [comment]
@jjohnstn  Would you please kindly check the update patch? Thanks. 

https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/360

**Comment by jjohnstn** [comment]
Closing with merge of #360
