### ISSUE TITLE
Issues with remove overridden assignment with combine statement results

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#38]
Comments can be lost with new Remove overridden assignment with combine statement.

Input:

	IParameter parameter = null;
				// get the parameter from the command
				parameter = command.getParameter(key);
Output

	IParameter parameter = command.getParameter(key);

Desired
				// get the parameter from the command
                              IParameter parameter = command.getParameter(key);

To test use cleanup on org.eclipse.core.commands.ParameterizedCommand from platform.ui

**Comment by tsmaeder** [comment]
So looking at this example: 
```
int totalHeight = 0;
int innerHeight = 0;
int topMargin= 0;
int bottomMargin = 0;
totalHeight = topMargin + innerHeight + bottomMargin;
```

I believe the only way moving the initialization can lead to problem is if we reference a name that has not been declared at the location of the variable init statement for `totaHeight`. We know it's not a method, because that would already be caught because of potential side effects. So the remaining values to be declared can be
* a local variable
* a field in locally declared class. If the class was declared elsewhere, it would also be in scope at the first variable declaration.

In either case, the name used in the init expression must be declared between the end of the overridden initializer and the beginning of the overriding assignment.  We already handle a case where we can't move the initialization up, this would just be checking that all names used in the init expression are not declared in that range.

Makes sense @vogella ?

**Comment by vogella** [comment]
Sounds fine to me @tsmaeder

**Comment by tsmaeder** [comment]
> Comments can be lost with new Remove overridden assignment with combine statement.

I'm not sure about that: how about this:
```
int totalHeight= 33;
...
// the component is now initialized
int total height = 55;
...
```
What I mean is: moving the comment is sometimes the right thing to do, sometimes it's not. How can we tell?

**Comment by vogella** [comment]
I suggest to never delete a command and either leave it there is was or move it also, whatever this easier to implement. Or only fix the compiler issue and accept that some comments needs manual fixes, which is also fine for me in case the implementation of handling comments is realatively complex. Perfect is IMHO the enemy of good.
