### ISSUE TITLE
QuickFix fails to propose import

### ISSUE THREAD

**Issue by dhmartin** [eclipse-jdt/eclipse.jdt.ui#485]
Used to work on eclipse 2022-12 and now fails just after upgrading to 2023-03.

Try this:

	public static void main(String[] args) {
		Date d1= new Date();

		Date d2;
		d2=new Date();
	}

Check QuickFix: `import java.util.Date` is proposed only with the standalone declaration for `d2`, but not when trying to declare and assign on a row. Not just for Date, seems to fail for different API classes.

David

**Comment by trancexpress** [comment]
Works as expected if I revert: https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/546a6978432fa5f2b01083919364848dd89805dc

@jjohnstn could you take a look here? In the snippet from the description, quick fixes for importing `Date` are suggested only when hovering at `Date` at the line `Date d2;`. Seems to have broken with the fix for #349.

**Comment by jjohnstn** [comment]
Looking at it.

**Comment by trancexpress** [comment]
> Looking at it.

Thanks!
