### ISSUE TITLE
Java Formatter does not honor new line after annotations on parameters

### ISSUE THREAD

**Issue by lynntanksley** [eclipse-jdt/eclipse.jdt.ui#596]
Have this selection in the formatter
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/87991620/192a2ccb-da2f-448b-9279-88eef9b3343f)
which translates to 

< setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="do not insert"/>

but still code is formatted like this:

> protected Object initialize(@SuppressWarnings("unused")
> Core<?> parent, Physical physical)

Instead of 

> protected Object initialize(@SuppressWarnings("unused") Core<?> parent, Physical physical)

Saw this in Eclipse 2023-03 and so tried 2022-12 and 2022-09 and they seem to have the same issue.

**Comment by jjohnstn** [comment]
@lynntanksley I am unable to reproduce this.  I don't have a Core or Physical class so I have:
```

package tests;

import java.util.Collection;

public class TestAnnotation {

	public void foo(@SuppressWarnings("unused") int a, int b) {
	}

	protected Object initialize(@SuppressWarnings("unused") Collection<?> parent, String physical) {
		return null;
	}

}
```

Specifying the setting makes the newline appear.  Without the setting, it doesn't do anything.

Can you provide more info?  Are you using the default formatter settings and if not, does it work when you switch back to default?  If you have custom settings and the default works, please provide your settings.  Does the sample I provided still exhibit the problem for you?  If not, can you provide the source being formatted or if not, can you provide a sample java file that exhibits the problem?

**Comment by lynntanksley** [comment]
Ok, thanks for the response. I found that we have a file called this, left over from 2018 version of eclipse:

> .settings/org.eclipse.jdt.core.prefs

I changed back to default prefs and deleted that file and then imported my custom profile again. Now that formatting works. Is the org.eclipse.jdt.core.prefs no longer needed?

**Comment by jjohnstn** [comment]
The .settings/org.eclipse.jdt.core.prefs file in your project contains project-specific core preferences that are saved from session to session.  Any preferences that aren't specified in that file will either use the workspace preferences or use default values.  Some projects save these in their repos so everyone is using the same settings (e.g. so all files format to some consistent rule set).  If your previous settings file has some settings you wish to use, simply set the preferences again, specifying to configure project specific preferences.  Otherwise, if you are happy with the workspace settings and defaults, then you are fine.

**Comment by lynntanksley** [comment]
Okay, this explains a lot. I think I've got it now. Thanks for the help.
