### ISSUE TITLE
List of projects within a working set often are displayed duplicated 

### ISSUE THREAD

**Issue by aino-gautam** [eclipse-jdt/eclipse.jdt.ui#605]
As you can see in the screenshot project list is often displayed duplicated. I have noticed this to happen specially in the working sets in a list of working sets down the order. 

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/7cd033a2-4275-4aad-af66-a60cc6112c0f)

**Version of eclipse in use**

Version: 2023-03 (4.27.0)
Build id: 20230309-1520

**Comment by jjohnstn** [comment]
Hi @aino-gautam I am unable to reproduce this with vanilla 2023-03 SDK or 2023-06 RC1 with about 6 Java projects.  Is there any more information you can provide on how to reproduce this like what other plug-ins/features you have installed?

**Comment by aino-gautam** [comment]
@jjohnstn Here is a link to my eclipse installation details taken directly from about eclipse dialog. Below you will also find an error log visible the same dialog .. related to binding conflicts. 

On my installation it occurs for every 2nd working set I create. And it repeats each time... sort of a standar feature. I also use git repository groups. Not sure if they could affect each other. 

What else can I share that might help ? 

[https://gist.github.com/aino-gautam/65341adf4a8bf99ab55841b324e2520e](url)

!SESSION 2023-06-03 16:32:07.765 -----------------------------------------------
eclipse.buildId=4.27.0.20230309-1200
java.version=17.0.7
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file /home/dga/dev/gitdev-workspace/.metadata/.bak_0.log
Created Time: 2023-06-03 16:32:13.016

!ENTRY ch.qos.logback.classic 1 0 2023-06-03 16:32:13.016
!MESSAGE Logback config file: /home/dga/dev/gitdev-workspace/.metadata/.plugins/org.eclipse.m2e.logback/logback.2.1.100.20230106-1511.xml

!ENTRY org.eclipse.jface 2 0 2023-06-03 16:32:17.108
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-06-03 16:32:17.108
!MESSAGE A conflict occurred for CTRL+SHIFT+F11:
Binding(CTRL+SHIFT+F11,
	ParameterizedCommand(Command(org.eclipse.eclemma.ui.commands.CoverageLast,Coverage,
		Coverage,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		WorkbenchHandlerServiceHandler("org.eclipse.eclemma.ui.commands.CoverageLast"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+F11,
	ParameterizedCommand(Command(org.eclipse.tcf.te.tcf.ui.toolbar.command.historyLast,Execute Last Action,
		,
		Category(org.eclipse.tcf.te.ui.commands.category,Target Explorer Commands,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.tcf.te.tcf.ui.toolbar.command.historyLast"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,gtk,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-06-03 16:32:17.108
!MESSAGE A conflict occurred for ALT+CTRL+P:
Binding(ALT+CTRL+P,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.preparechangelog,Prepare Changelog,
		Prepares Changelog,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		WorkbenchHandlerServiceHandler("org.eclipse.linuxtools.changelog.core.preparechangelog"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+CTRL+P,
	ParameterizedCommand(Command(org.eclipse.m2e.profiles.ui.commands.selectMavenProfileCommand,Select Maven Profiles,
		,
		Category(org.eclipse.ui.category.window,Window,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.m2e.profiles.ui.commands.selectMavenProfileCommand"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.update.configurator 4 0 2023-06-03 16:35:18.944
!MESSAGE Can't find bundle for base name feature, locale en_IN

**Comment by aino-gautam** [comment]
Additional note - it doesnt occur on my Mac M2. Will confirm if its the same build.

**Comment by aino-gautam** [comment]
And is there  a way I can easily export all installation summary including plugin list ?

**Comment by jjohnstn** [comment]
You could take a screen snapshot of your Installed Software tab.  Did you start with an EPP product (e.g. Eclipse for Enterprise Java and Web Developers)?  I see a few packages referenced above in your key conflicts that I could pursue installing.

**Comment by aino-gautam** [comment]
Please see installation summary screenshots. Also kindly help triage the issue #611 meant to address these struggles in reporting issues. 

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/733515ce-4a8f-477c-a90f-b4157afcc563)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/59bf2398-8d02-491d-b928-5973747f135b)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/feafb59c-27ce-44bd-9af5-33abdfbb1f67)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/bd4c2c78-d254-4f36-9e7f-4a0ea4a30f06)

And yes I think its EPP. If I recall right I downloaded this version -
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/519118/a15ebc48-ab30-4493-94e5-9df90190eb0c)

Please suggest if I should pursue any chain of thoughts to help pinpoint the issue better. Looking into the key conflicts errors now.

**Comment by jjohnstn** [comment]
Hi @aino-gautam Thanks for the info.  I tried downloading the vanilla 2023-03 Eclipse IDE for Enterprise Java and Web Developers and creating a variety of projects, but unfortunately I can't reproduce the problem (I just created default projects of the various types and adding them to multiple working sets).   That said, I noticed you have the following additions installed:

1. CDT tools (don't think this is the issue)
2. Docker tooling from Linux Tools (won't be the issue)
3. ChangeLog plug-in from Linux Tools (won't be the issue)
4. Eclipse Jetty feature
5. FluentMark editor
6. JBoss Freemarker feature
7. Git GitFlow
8. GWT Eclipse plug-in
9. Git optional LFS support
10. Git option ssh support using JCraft
11. Linux Tools Javadocs (won't be this)
12. Javascript Development tools
13. Linux Tools JDT Docker Launcher (won't be this)
14. Mylyn Wikitext
15. Pydev for Eclipse
16. Linux Tools Systemtap (won't be this)

Of these, there a number I am unfamiliar with.  I believe one of these is the culprit (not the ones I have added "won't be this").  I work on Linux Tools and CDT and don't believe either of those will have caused the problem.

I would suggest try downloading a vanilla 2023-03 IDE for Enterprise Java and Web developers and importing all of your existing projects there.  Try and recreate your working sets and verify the problem does not occur (you may have some projects give errors due to missing additional features, but we aren't concerned with using this IDE, just finding out the culprit).  If that works fine for you, then we know it is the additions.

From there, try installing the various features above that I haven't designated as probably safe one by one and see if the problem surfaces.  I would start with Pydev as it uses a large assortment of extensions and might well be the cause of the problem.

Using the separate IDE should help to keep your current work set-up intact but if you have any projects that aren't restoreable by a repo system such as git, I would suggest copying them to ensure the .project or .settings files aren't overwritten in the import stage.

**Comment by aino-gautam** [comment]
I can confirm the issue was PyDev . Uninstalling it fixed the issue and a bunch of others I was facing. including losing out on  editor vs. file associations consistently. Thanks for the pointers and support. Much appreciated.
