### ISSUE TITLE
From: Nested records have unneeded import

### ISSUE THREAD

**Issue by arithauth** [eclipse-jdt/eclipse.jdt.ui#864]
Nested class in record has unneeded import. eclipse-jdt/eclipse.jdt.ui#890

This is because the organizing import cannot find record components' parent nodes.

[Bindings.java](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/9930873f5d437241a7654e96cd51cc1aeb8a90f8/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/dom/Bindings.java#L1218-L1220) is in charge of finding a parent. If the parent was not found from its child, the child is considered not declared in the scope of parent and child requests unneeded import.
```
if (lastLocation == decl.getBodyDeclarationsProperty()
    || lastLocation == decl.getJavadocProperty()
    || (decl instanceof EnumDeclaration && lastLocation == EnumDeclaration.ENUM_CONSTANTS_PROPERTY)) {
```
The third line would be for this situation:
```
enum A {
    X(new B());

    A(Object o) {}
    class B {}
}
```
It is necessary to find it also in this place:
```
record A(B b) {
    class B {}
}
```
So I need to add this condition to the if statement.
`|| (decl instanceof RecordDeclaration && lastLocation == RecordDeclaration.RECORD_COMPONENTS_PROPERTY)`

However I don't  know how to make pr. Could someone please make it?

I wrote test codes: [eclipse.jdt.ui-master/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/core/ImportOrganizeTest16.java](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/13030806/ImportOrganizeTest16.txt)

**Comment by jjohnstn** [comment]
Hi @arithauth Thanks.  I can make the PR but I would suggest you sign the ECA (Eclipse Contributor Agreement) as you are submitting a new test which has no licensing info in it.  I would assume that you merged code from ImportOrganizeTest and ImportOrganizeTest1d8 but you would need to confirm that.  If you do confirm that, the license can be attributed to IBM, the original implementors that the code was based on and then have a single copyright year of 2023 since it is a brand new file.  If you can't/won't sign the ECA, then I'll create a test from scratch.

**Comment by arithauth** [comment]
@jjohnstn I read Eclipse Contributor Agreement but I don't want to create eclipse profile by my real name. I am sorry; Can you make PR and tests sometime, since my test code is almost the copy of "ImportOrganizeTest"s. Thank you for your time and help.

**Comment by jjohnstn** [comment]
No problem @arithauth , I created #892  This PR can be closed.  Thanks for looking into it.
