### ISSUE TITLE
UI Error when a generated Field (lombok) is used on annotation

### ISSUE THREAD

**Issue by c-koell** [eclipse-jdt/eclipse.jdt.ui#865]
We are using lombok 1.18.30 within eclipse 2023-09.

If we use the @FieldNameConstants Annotation a InnerClass with static final Fields will be generated.

There is no Compile Error but we see a Error on the Classs itself
![Eclipse IDE](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/4134346/8453bd6c-6bf8-470b-b4cf-83b77892aff6)

The Problems View is empty, and the code works if you run it ...

You will find a sample eclipse project here
[Sample-Project.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/13043088/Sample-Project.zip)

You must start eclipse with lombok installed
Sample eclipse.ini
```
-javaagent:C:/Temp/lombok-1.18.30.jar
-Xbootclasspath/a:C:/Temp/lombok-1.18.30.jar
```
You will also find [here](https://projectlombok.org/setup/eclipse) the docu regarding installation.

**Comment by iloveeclipse** [comment]
I assume Lombock rewrites class files "under der hood" and JDT UI isn't notified about that or uses what AST sees in the source of the Person.java which doesn't contain any "Fields" inner class. Not sure if that can be fixed in JDT UI.
Probably you should open an issue at Lombock tracker https://github.com/projectlombok/lombok/issues for the Eclipse integration part of Lombok.

**Comment by c-koell** [comment]
Created a issue in lombok project https://github.com/projectlombok/lombok/issues/3529

**Comment by c-koell** [comment]
This Bug will be fixed in Lombok .. thanks
