### ISSUE TITLE
Error in testInnerClassWithNestedAnnotationIsFound[JUnit4] since I20231211-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#999]
See https://download.eclipse.org/eclipse/downloads/drops4/I20231211-1800/testresults/html/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Regression from https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/953

The test is "aborted" but intention was that it should be marked as "skipped". I see other tests that also use "assume" but are don't marked as aborted. Probably the reason is that the test is parametrized. 
**We should make sure that this test does not show as an error if the intention was to skip it.**

**Comment by iloveeclipse** [comment]
@fedejeanne: could you please look at it?

**Comment by fedejeanne** [comment]
Makes sense, I just checked [these results](https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/master/139/testReport/AutomatedSuite%20org.eclipse.jdt.junit.tests.JUnitJUnitTests%20org.eclipse.jdt.junit.tests/JUnitTestFinderTest/) and they look just fine.
I also saw that you provided a fix already in #1001 . 

I'll take a look again if that PR doesn't solve the problem, ok?

**Comment by fedejeanne** [comment]
I can check it, no problem. 

Maybe you can help me find the stack trace of the failed test in the nightly build? I looked around but couldn't find the right stack traces. If I could get my hands on those then I could at least see which runner is being used.

I looked around these places:
* https://download.eclipse.org/eclipse/downloads/drops4/I20231211-1800/logs.php#console
* https://ci.eclipse.org/jdt/
* https://ci.eclipse.org/releng/

**Comment by fedejeanne** [comment]
Also here: https://download.eclipse.org/eclipse/downloads/drops4/I20231211-1800/buildlogs/mb060_run-maven-build_output.txt

**Comment by iloveeclipse** [comment]
The xml report is attached on this ticket but it doesn't contain stack trace, and I don't see any other output produced.

Workspace log also doesn't show anything useful: https://download.eclipse.org/eclipse/downloads/drops4/I20231211-1800/testresults/ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/org.eclipse.jdt.ui.tests.AutomatedSuite.txt

**Comment by iloveeclipse** [comment]
I've merged https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1001 now, but not closing this one yet, because I'm not sure if #1001 fixes **this** issue too. Will see tomorrow. I somehow have a feeling there lurks some JUnit result formatter in the platform aggregator build that also need to be adopted.

**Comment by fedejeanne** [comment]
Maybe @merks knows where the stack traces of the failed tests for the [nightly build](https://download.eclipse.org/eclipse/downloads/drops4/I20231211-1800/testresults/html/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html) could be found? Something that shows the stack of the "skipped" test `org.eclipse.jdt.junit.tests.JUnitTestFinderTest.testInnerClassWithNestedAnnotationIsFound()`

**Comment by iloveeclipse** [comment]
> Will see tomorrow. I somehow have a feeling there lurks some JUnit result formatter in the platform aggregator build that also need to be adopted.

The change had no influence on what's reported during SDK build.
https://download.eclipse.org/eclipse/downloads/drops4/I20231212-1800/testresults/html/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

There is code that generates html pages in releng, that must be found & fixed.

**Comment by jukzi** [comment]
i don't understand the build reports anymore: 
Errors=1 - but none shown?
https://download.eclipse.org/eclipse/downloads/drops4/I20231214-1800/testresults/html/org.eclipse.jdt.ui.tests_ep431I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/d8bba87b-1130-4f89-9566-8f7c863ff01a)

jenkins says 3 errors but lists only 2:
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-mac64-java17/34/
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/27aadac9-eec1-4680-acca-13c979a2c2f2)

**Comment by iloveeclipse** [comment]
> i don't understand the build reports anymore:

Looking at the generated xml files, I don't see "error" or "aborted" **test case** - the only mention of an abort & error is in the **testsuite** element itself, which makes me think the **XML reporter** configured in ant is to blame here, not the html report **generator**.

See here: this is only place in xml file that shows the problem
`<testsuite aborted="1" errors="1" failures="0" id="0" name="AutomatedSuite" package="org.eclipse.jdt.ui.tests" skipped="6" tests="3513" time="1039.483" timestamp="2023-12-15T05:09:46">` 

The question is: *who* generates this **xml** that is being processed by `TestResultsGenerator`? That one need to be fixed.

@sravanlakkimsetti , @akurtakov : I believe you could have an idea.

**Comment by akurtakov** [comment]
@iloveeclipse https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/LegacyXmlResultFormatter.java should be a hint. Unfortunately, I don't remember much more.

**Comment by iloveeclipse** [comment]
@fedejeanne : could you please check if you could see anything suspicious in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/LegacyXmlResultFormatter.java ?

If not, could you please check if you can change your original test to avoid "abort" case?

**Comment by fedejeanne** [comment]
Status update: It seems to be already known, that "ABORTED" == "SKIPPED", which is why some parts of the code already interpret it like that

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/2205684/bc1b5b2d-a9af-447e-9655-f2cd4fceb76f)

I'm currently doing some manual testing with some JUnit4/5 classes and looking at the generated XML. I'll provide a PR tomorrow.

**Comment by fedejeanne** [comment]
I did some tests and a lot of reading and it turns out everything works as expected: the difference between _ABORTED_ and _SKIPPED_ is that an _aborted_ test starts but never finishes while a _skipped_ test never really starts.

This behavior is consistent across JUnit4 and JUnit5 and can be achieved in different ways:

## Skipping a test
* In JUnit4: annotate the test with `@Ignore`
* In JUnit5: annotate the test with `@Disabled` or some dynamic annotation like `@EnabledOn...`, `@DisabledOn...`, `@EnabledIf...` [etc.](https://www.baeldung.com/junit-5-conditional-test-execution)

## Aborting a test
* In JUnit4: use `org.junit.Assume` or throw an `org.junit.AssumptionViolatedException`
* In JUnit5: use `org.junit.jupiter.api.Assumptions` or throw a `org.opentest4j.TestAbortedException` /  `org.junit.AssumptionViolatedException`

## Summary
> The test is "aborted" but intention was that it should be marked as "skipped". 

Wrong: _aborted_ is correct

> I see other tests that also use "assume" but are don't marked as aborted. 

Where? Those are probably wrong and should be marked as _aborted_, not skipped.

> We should make sure that this test does not show as an error if the intention was to skip it.

I don't think that has anything to do with the _aborted_ / _skipped_ tests. Tests marked as _error_ are those which end up throwing an exception **other than `AssertionError`** (if an assertion fails then it's a _failed_ test). I'll look into it.

**Comment by fedejeanne** [comment]
> I don't think that has anything to do with the aborted / skipped tests. Tests marked as error are those which end up throwing an exception other than AssertionError (if an assertion fails then it's a failed test). I'll look into it.

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1689

**Comment by fedejeanne** [comment]
Now that https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1690 is merged, the real problem became visible: it's not the fact that a test is being aborted but a missing file in the test. I find it odd though that the tests work in GA (e.g. [here](https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/view/change-requests/job/PR-1032/4/testReport/AutomatedSuite%20org.eclipse.jdt.junit.tests.JUnitJUnitTests%20org.eclipse.jdt.junit.tests/JUnit5TestFinderJupiterTest/)) but they fail in the nightly builds. The test resources are being packaged though, so they should be there.

![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/2205684/0aea0276-22ac-4ee5-9f71-7578af667be2)

Does anyone have an idea what are the nightly builds doing differently or why is the file not being found in them?

I apologize in advance for late responses. If someone else wants to take the lead on this one, I would appreciate it.

**Comment by iloveeclipse** [comment]
Please add missing files (I assume folder) to the build.properties of the bundle.

**Comment by fedejeanne** [comment]
> Please add missing files (I assume folder) to the build.properties of the bundle.

It's already there: https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui.tests/build.properties#L17

**Comment by iloveeclipse** [comment]
1) Can you please check if the test bundle itself after the build contain the required files?
2) Which code is supposed to use these files, and how they are accessed?

I assume either the files are **not** packaged properly, or they are not properly fetched at runtime. Typical problem is that one tries to access files that (in SDK build) packaged inside a jar and that works for IDE tests where they are "in place", and doesn't in the final build.

**Comment by fedejeanne** [comment]
> 1. Can you please check if the test bundle itself after the build contain the required files?

I checked in the generated [repository (ZIP)](https://download.eclipse.org/eclipse/downloads/drops4/I20231231-2320/download.php?dropFile=repository-I20231231-2320.zip) and the file is there. It's being packaged inside a JAR though, so that might be a problem.

> 2. Which code is supposed to use these files, and how they are accessed?

The path to the file is specified like this:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/6cc39d9a5697dc92738aa7e9f24cb976e802f699/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnit5TestFinderJupiterTest.java#L60-L64

And its content is read like this:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/6cc39d9a5697dc92738aa7e9f24cb976e802f699/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/junit/tests/JUnit5TestFinderJupiterTest.java#L144
